// Code generated by MockGen. DO NOT EDIT.
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_registration_usecase.go -package=mocks -write_package_comment=false -write_source_comment=false github.com/Noraluk/backend-challenge-7solutions/internal/ports RegistrationUseCase
//

package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Noraluk/backend-challenge-7solutions/internal/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationUseCase is a mock of RegistrationUseCase interface.
type MockRegistrationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationUseCaseMockRecorder
	isgomock struct{}
}

// MockRegistrationUseCaseMockRecorder is the mock recorder for MockRegistrationUseCase.
type MockRegistrationUseCaseMockRecorder struct {
	mock *MockRegistrationUseCase
}

// NewMockRegistrationUseCase creates a new mock instance.
func NewMockRegistrationUseCase(ctrl *gomock.Controller) *MockRegistrationUseCase {
	mock := &MockRegistrationUseCase{ctrl: ctrl}
	mock.recorder = &MockRegistrationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationUseCase) EXPECT() *MockRegistrationUseCaseMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockRegistrationUseCase) Register(arg0 context.Context, arg1 dto.RegistrationInput) (dto.UserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(dto.UserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockRegistrationUseCaseMockRecorder) Register(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRegistrationUseCase)(nil).Register), arg0, arg1)
}
