// Code generated by MockGen. DO NOT EDIT.
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_authentication_usecase.go -package=mocks -write_package_comment=false -write_source_comment=false github.com/Noraluk/backend-challenge-7solutions/internal/ports AuthenticationUseCase
//

package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Noraluk/backend-challenge-7solutions/internal/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticationUseCase is a mock of AuthenticationUseCase interface.
type MockAuthenticationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationUseCaseMockRecorder
	isgomock struct{}
}

// MockAuthenticationUseCaseMockRecorder is the mock recorder for MockAuthenticationUseCase.
type MockAuthenticationUseCaseMockRecorder struct {
	mock *MockAuthenticationUseCase
}

// NewMockAuthenticationUseCase creates a new mock instance.
func NewMockAuthenticationUseCase(ctrl *gomock.Controller) *MockAuthenticationUseCase {
	mock := &MockAuthenticationUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthenticationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationUseCase) EXPECT() *MockAuthenticationUseCaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthenticationUseCase) Login(arg0 context.Context, arg1 dto.LoginInput) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthenticationUseCaseMockRecorder) Login(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthenticationUseCase)(nil).Login), arg0, arg1)
}
