// Code generated by MockGen. DO NOT EDIT.
//
// Generated by this command:
//
//	mockgen -source=internal/adapters/mongodb/user_repository.go -destination=internal/mocks/mock_user_collection.go -package=mocks -mock_names=userCollection=MockUserCollection -write_package_comment=false -write_source_comment=false
//

package mocks

import (
	context "context"
	reflect "reflect"

	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	options "go.mongodb.org/mongo-driver/v2/mongo/options"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCollection is a mock of userCollection interface.
type MockUserCollection struct {
	ctrl     *gomock.Controller
	recorder *MockUserCollectionMockRecorder
	isgomock struct{}
}

// MockUserCollectionMockRecorder is the mock recorder for MockUserCollection.
type MockUserCollectionMockRecorder struct {
	mock *MockUserCollection
}

// NewMockUserCollection creates a new mock instance.
func NewMockUserCollection(ctrl *gomock.Controller) *MockUserCollection {
	mock := &MockUserCollection{ctrl: ctrl}
	mock.recorder = &MockUserCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCollection) EXPECT() *MockUserCollectionMockRecorder {
	return m.recorder
}

// CountDocuments mocks base method.
func (m *MockUserCollection) CountDocuments(arg0 context.Context, arg1 any, arg2 ...options.Lister[options.CountOptions]) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountDocuments", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDocuments indicates an expected call of CountDocuments.
func (mr *MockUserCollectionMockRecorder) CountDocuments(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDocuments", reflect.TypeOf((*MockUserCollection)(nil).CountDocuments), varargs...)
}

// DeleteOne mocks base method.
func (m *MockUserCollection) DeleteOne(arg0 context.Context, arg1 any, arg2 ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(*mongo.DeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockUserCollectionMockRecorder) DeleteOne(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockUserCollection)(nil).DeleteOne), varargs...)
}

// Find mocks base method.
func (m *MockUserCollection) Find(arg0 context.Context, arg1 any, arg2 ...options.Lister[options.FindOptions]) (*mongo.Cursor, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(*mongo.Cursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserCollectionMockRecorder) Find(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserCollection)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockUserCollection) FindOne(arg0 context.Context, arg1 any, arg2 ...options.Lister[options.FindOneOptions]) *mongo.SingleResult {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*mongo.SingleResult)
	return ret0
}

// FindOne indicates an expected call of FindOne.
func (mr *MockUserCollectionMockRecorder) FindOne(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockUserCollection)(nil).FindOne), varargs...)
}

// FindOneAndUpdate mocks base method.
func (m *MockUserCollection) FindOneAndUpdate(arg0 context.Context, arg1, arg2 any, arg3 ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOneAndUpdate", varargs...)
	ret0, _ := ret[0].(*mongo.SingleResult)
	return ret0
}

// FindOneAndUpdate indicates an expected call of FindOneAndUpdate.
func (mr *MockUserCollectionMockRecorder) FindOneAndUpdate(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneAndUpdate", reflect.TypeOf((*MockUserCollection)(nil).FindOneAndUpdate), varargs...)
}

// InsertOne mocks base method.
func (m *MockUserCollection) InsertOne(arg0 context.Context, arg1 any, arg2 ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockUserCollectionMockRecorder) InsertOne(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockUserCollection)(nil).InsertOne), varargs...)
}
